# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Eduspike Web Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./eduspike-web

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eduspike-web

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: ./eduspike-web
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      working-directory: ./eduspike-web
    - run: npm run build --if-present
      working-directory: ./eduspike-web
    - name: Deploy
      working-directory: ./eduspike-web
      uses: peaceiris/actions-gh-pages@v3
      with:
        # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # directory to deploy
